# Generated by Django 2.2 on 2019-04-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('matches', models.IntegerField()),
                ('win_match', models.IntegerField()),
                ('lost_match', models.IntegerField()),
                ('points', models.IntegerField(max_length=2)),
            ],
        ),
    ]
