# Generated by Django 2.2 on 2019-04-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointstable', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointstable',
            name='points',
            field=models.IntegerField(),
        ),
    ]
