# Generated by Django 2.2 on 2019-04-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointstable', '0002_auto_20190404_0052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointstable',
            name='lost_match',
        ),
        migrations.RemoveField(
            model_name='pointstable',
            name='matches',
        ),
        migrations.RemoveField(
            model_name='pointstable',
            name='win_match',
        ),
        migrations.AddField(
            model_name='pointstable',
            name='lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointstable',
            name='no_result',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointstable',
            name='nrr',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='pointstable',
            name='played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointstable',
            name='won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pointstable',
            name='points',
            field=models.FloatField(default=0.0),
        ),
    ]
